spiralation_site_homepage:
    pattern:  /index
    defaults: { _controller: SpiralationSiteBundle:Index:index }
    
spiralation_site_loginpage:
    pattern:  /login
    defaults: { _controller: SpiralationSiteBundle:Login:index }

create_volunteer:
    pattern:  /register
    defaults: { _controller: SpiralationSiteBundle:Register:volunteer }

create_volunteer_android:
    pattern:  /registerAndroid
    defaults: { _controller: SpiralationSiteBundle:Register:formAndroid }

create_organization:
    pattern:  /addorganization
    defaults: { _controller: SpiralationSiteBundle:Register:organization }

